# Type check the Android backend. Use this with
#   uv run poe typecheck-android
# or
#   mypy --config-file=mypy-android.ini

[mypy]
# 3.13 is the minimum supported Python version for the Android backend
python_version = 3.13
disable_error_code = import-not-found
exclude = (.venv|kivy|recipes|testbed/build)/
mypy_path = typings
files = bleak, tests, examples, testbed
platform = android

[mypy-bleak.backends.p4android.*]
ignore_errors = True

# host-side test runner dependencies without type stubs
[mypy-serial.*,uiautomator2.*]
ignore_missing_imports = True
