# Use this with 
#   mypy --config-file=mypy-android.ini

[mypy]
python_version = 3.10
disable_error_code = import-not-found
exclude = (.venv|kivy|recipes|examples/briefcase)/
mypy_path = typings_android
packages = bleak, tests, examples
platform = android

[mypy-bleak.backends.p4android.*]
ignore_errors = True

[mypy-android.*]
ignore_errors = True

[mypy-java.*]
ignore_errors = True