[tox]
envlist = py310, py310-rubicon, typecheck, typecheck-rubicon, lint
labels =
    py3.10 = py310, py310-rubicon
    py3.11 = py311, py311-rubicon
    py3.12 = py312, py312-rubicon
    py3.13 = py313, py313-rubicon
    py3.14 = py314, py314-rubicon
    typecheck = typecheck, typecheck-rubicon

[testenv]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --only main,test
commands =
    poetry run pytest tests {posargs} -v --import-mode importlib

[testenv:py{310,311,312,313,314}-rubicon]
platform = darwin
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --only main,test --extras "rubicon"
setenv =
    BLEAK_COREBLUETOOTH_FRAMEWORK = rubicon-objc
commands =
    poetry run pytest tests {posargs} -v --import-mode importlib

[testenv:typecheck]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --with typecheck
commands =
    poetry run mypy
    poetry run pyright

[testenv:typecheck-rubicon]
platform = darwin
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --with typecheck --extras "rubicon"
setenv =
    BLEAK_COREBLUETOOTH_FRAMEWORK = rubicon-objc
commands =
    poetry run mypy --config-file mypy-rubicon-objc.ini
    poetry run pyright --project pyrightconfig-rubicon-objc.json

[testenv:lint{,-checkonly}]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --only lint
commands =
    !checkonly: poetry run isort . docs
    checkonly: poetry run isort . docs --check --diff
    !checkonly: poetry run black .
    checkonly: poetry run black . --check --diff
    poetry run flake8 . --count --show-source --statistics

[testenv:docs]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry sync --only docs
commands =
    poetry run make -C docs html
