import decimal
import sys
from ctypes import CDLL
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    NewType,
    Optional,
    Sequence,
    SupportsIndex,
    TypeVar,
    overload,
)

from rubicon.objc.runtime import objc_id

if sys.version_info < (3, 11):
    from typing_extensions import Self
else:
    from typing import Self

if sys.version_info < (3, 12):
    from typing_extensions import Buffer
else:
    from collections.abc import Buffer

class ObjCInstance:
    pass

class objc_method:
    def __init__(self, py_method: Callable[..., Any]) -> None: ...

class objc_classmethod:
    def __init__(self, py_method: Callable[..., Any]) -> None: ...

def objc_const(dll: CDLL, name: str) -> ObjCInstance: ...

NSKeyValueObservingOptions = NewType("NSKeyValueObservingOptions", int)

class NSObject(ObjCInstance):
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Optional[Self]: ...
    def addObserver_forKeyPath_options_context_(
        self,
        observer: NSObject,
        keyPath: str,
        options: NSKeyValueObservingOptions,
        context: int,
    ) -> None: ...
    def removeObserver_forKeyPath_(self, observer: NSObject, keyPath: str) -> None: ...
    @classmethod
    def __init_subclass__(cls, /, protocols: Sequence[Any] = []) -> None: ...

class Protocol(ObjCInstance): ...
class NSString(NSObject): ...

class NSData(NSObject):
    def initWithBytes_length_(self, bytes: Buffer, length: int) -> Self: ...
    @property
    def length(self) -> int: ...
    def getBytes_length_(self, buffer: bytes, length: int) -> None: ...
    @overload
    def __getitem__(self, index: SupportsIndex) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> memoryview: ...

class NSNumber(NSObject): ...
class NSDecimalNumber(NSObject): ...

T = TypeVar("T")
T2 = TypeVar("T2")

class NSArray(NSObject, Generic[T]):
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> NSArray[T]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __contains__(self, item: T) -> bool: ...
    def index(self, value: T) -> int: ...
    def count(self, value: T) -> int: ...
    def copy(self) -> Self: ...
    def initWithArray_(self, array: Sequence[T2]) -> NSArray[T2]: ...

K = TypeVar("K")
V = TypeVar("V")

class NSDictionary(NSObject, Generic[K, V]):
    def __getitem__(self, item: K) -> V: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: K) -> bool: ...
    def get(self, item: K, default: Optional[V] = None) -> Optional[V]: ...
    def keys(self) -> NSArray[K]: ...
    def values(self) -> NSArray[V]: ...
    def items(self) -> Iterator[tuple[K, V]]: ...
    def copy(self) -> Self: ...

@overload
def py_from_ns(nsobj: NSString) -> str: ...
@overload
def py_from_ns(nsobj: NSData) -> bytes: ...
@overload
def py_from_ns(nsobj: NSDictionary[Any, Any]) -> dict[Any, Any]: ...
@overload
def py_from_ns(nsobj: NSArray[Any]) -> list[Any]: ...
@overload
def py_from_ns(nsobj: NSNumber) -> bool | int | float: ...
@overload
def ns_from_py(pyobj: str) -> NSString: ...
@overload
def ns_from_py(pyobj: bytes) -> NSData: ...
@overload
def ns_from_py(pyobj: decimal.Decimal) -> NSDecimalNumber: ...
@overload
def ns_from_py(pyobj: dict[Any, Any]) -> NSDictionary[Any, Any]: ...
@overload
def ns_from_py(pyobj: list[Any]) -> NSArray[Any]: ...
@overload
def ns_from_py(pyobj: bool | int | float) -> NSNumber: ...
def objc_property(
    vartype: objc_id | int | float | bool | bytes | object | None = objc_id,
    weak: bool = False,
) -> Any: ...
