import typing

import android.os
import java
import java.lang
import java.util

class WifiP2pDnsSdServiceInfo(WifiP2pServiceInfo):
    @staticmethod
    def newInstance(instanceName: str | java.lang.String, serviceType: str | java.lang.String, txtMap: java.util.Map[java.lang.String, java.lang.String], /) -> WifiP2pDnsSdServiceInfo: ...

class WifiP2pDnsSdServiceRequest(WifiP2pServiceRequest):
    @typing.overload
    @staticmethod
    def newInstance() -> WifiP2pDnsSdServiceRequest: ...
    @typing.overload
    @staticmethod
    def newInstance(serviceType: str | java.lang.String, /) -> WifiP2pDnsSdServiceRequest: ...
    @typing.overload
    @staticmethod
    def newInstance(instanceName: str | java.lang.String, serviceType: str | java.lang.String, /) -> WifiP2pDnsSdServiceRequest: ...

class WifiP2pServiceInfo(android.os.Parcelable):
    SERVICE_TYPE_ALL: typing.ClassVar[int] = ...
    SERVICE_TYPE_BONJOUR: typing.ClassVar[int] = ...
    SERVICE_TYPE_UPNP: typing.ClassVar[int] = ...
    SERVICE_TYPE_VENDOR_SPECIFIC: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class WifiP2pServiceRequest(android.os.Parcelable):
    def describeContents(self) -> int: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    @typing.overload
    @staticmethod
    def newInstance(protocolType: int | java.jint | java.lang.Integer, /) -> WifiP2pServiceRequest: ...
    @typing.overload
    @staticmethod
    def newInstance(protocolType: int | java.jint | java.lang.Integer, queryData: str | java.lang.String, /) -> WifiP2pServiceRequest: ...
    def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class WifiP2pUpnpServiceInfo(WifiP2pServiceInfo):
    @staticmethod
    def newInstance(uuid: str | java.lang.String, device: str | java.lang.String, services: java.util.List[java.lang.String], /) -> WifiP2pUpnpServiceInfo: ...

class WifiP2pUpnpServiceRequest(WifiP2pServiceRequest):
    @typing.overload
    @staticmethod
    def newInstance() -> WifiP2pUpnpServiceRequest: ...
    @typing.overload
    @staticmethod
    def newInstance(st: str | java.lang.String, /) -> WifiP2pUpnpServiceRequest: ...
